[package]
name = "ray-tracing-in-one-weekend-webgpu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytemuck = "1.13.1"
tokio = { version = "1.29.1", features = ["full"] }
wgpu = "0.16.2"
